
[advisories]
notice = "deny"
unmaintained = "deny"
vulnerability = "deny"
yanked = "deny"
ignore = []

# This library uses the MPL-2 license.
#
# See https://www.mozilla.org/en-US/MPL/2.0/permissive-code-into-mpl/
[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
]
default = "deny"
confidence-threshold = 1.0
unlicensed = "deny"

[bans]
allow = []
deny = [
    # License is non-trivial
    { name = "ring" },
]
multiple-versions = "warn"
skip = []
skip-tree = [
    # It's a mess of duplicate dependencies as of version 0.16.0
    { name = "ipfs-api" }
]
wildcards = "warn"

[sources]
allow-git = [
    # TODO: Remove once rust-ipfs-api releases a version with basic auth
    "https://github.com/iamjpotts/rust-ipfs-api"
]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
